# Generated by Django 5.0.6 on 2024-05-13 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='albumImage',
            field=models.ImageField(blank=True, null=True, upload_to='albumImages/'),
        ),
    ]
